const AccountColumns: any = [
  {
    title: "Name",
    dataIndex: "AccountName",
    type: "string",
    order: null,
    edit: false,
    sort: true,
    input: "",
    search: true,
  },
  {
    title: "Code",
    dataIndex: "AccountCode",
    type: "string",
    order: null,
    edit: false,
    sort: false,
    input: "",
    search: true,
  },
  {
    title: "Plan",
    dataIndex: "PlanCode",
    type: "string",
    order: null,
    edit: false,
    sort: false,
    input: "",
    search: true,
  },
  {
    title: "Created On",
    dataIndex: "CreatedOn",
    type: "string",
    order: null,
    edit: false,
    sort: false,
    input: "",
    search: false,
  },
  {
    title: "Status",
    dataIndex: "Status",
    type: "string",
    order: null,
    edit: false,
    sort: false,
    input: "",
    search: true,
  },
];

const SchoolColumns: any = [
  {
    title: "Name",
    dataIndex: "SchoolName",
    type: "string",
    order: null,
    edit: false,
    sort: true,
    input: "",
    search: true,
  },
  {
    title: "Code",
    dataIndex: "SchoolCode",
    type: "string",
    order: null,
    edit: false,
    sort: false,
    input: "",
    search: true,
  },
  {
    title: "Location",
    dataIndex: "Location",
    type: "string",
    order: null,
    edit: false,
    sort: true,
    input: "",
    search: true,
  },
  // {
  //   title: "Created On",
  //   dataIndex: "CreatedOn",
  //   type: "string",
  //   order: null,
  //   edit: false,
  //   sort: false,
  //   input: "",
  //   search: true,
  // },
  {
    title: "Status",
    dataIndex: "Status",
    type: "string",
    order: null,
    edit: false,
    sort: false,
    input: "",
    search: true,
  },
];

const UserColumns: any = [
  {
    title: "Name",
    dataIndex: "UserName",
    type: "string",
    order: null,
    edit: false,
    sort: true,
    input: "",
    search: true,
  },
  {
    title: "EMail",
    dataIndex: "EMail",
    type: "string",
    order: null,
    edit: false,
    sort: false,
    input: "",
    search: true,
  },
  {
    title: "Schools",
    dataIndex: "SchoolCodes",
    type: "string",
    order: null,
    edit: false,
    sort: false,
  },
  // {
  //   title: "Created On",
  //   dataIndex: "CreatedOn",
  //   type: "string",
  //   order: null,
  //   edit: false,
  //   sort: false,
  //   input: "",
  //   search: false,
  // },
  {
    title: "Status",
    dataIndex: "Status",
    type: "status",
    order: null,
    edit: false,
    sort: false,
    input: "",
    search: false,
  },
];

const TicketHistory: any = [
  {
    title: "Ticket No.",
    dataIndex: "TicketNo",
    type: "string",
    order: null,
    edit: false,
    sort: true,
  },
  {
    title: "Issue",
    dataIndex: "Issue",
    type: "string",
    order: null,
    edit: false,
    sort: true,
    input: "",
    search: true,
  },
  {
    title: "Created By",
    dataIndex: "CreatedBy",
    type: "string",
    order: null,
    edit: false,
    sort: true,
    input: "",
    search: true,
  },
  {
    title: "Created On",
    dataIndex: "CreatedOn",
    type: "string",
    order: null,
    edit: false,
    sort: true,
    input: "",
    search: true,
  },
  {
    title: "Status",
    dataIndex: "Status",
    type: "string",
    order: null,
    edit: false,
    sort: true,
    input: "",
    search: true,
  },
];

const Students: any = [
  {
    title: "Admission No.",
    dataIndex: "AdmissionNo",
    type: "string",
    order: null,
    edit: false,
    sort: false,
    isLink: false,
  },
  {
    title: "Class",
    dataIndex: "Class",
    type: "string",
    order: null,
    edit: false,
    sort: true,
    isLink: false,
  },
  {
    title: "Roll No.",
    dataIndex: "RollNo",
    type: "string",
    order: null,
    edit: false,
    sort: false,
    isLink: false,
  },
  {
    title: "Name",
    dataIndex: "StudentName",
    type: "string",
    order: null,
    edit: false,
    sort: true,
    isLink: true,
  },
  {
    title: "Action",
    dataIndex: "StudentAction",
    type: "string",
    order: null,
    edit: false,
    sort: false,
    input: "",
    search: false,
  },
];

export { AccountColumns, SchoolColumns, UserColumns, TicketHistory, Students };
